import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../models/level_play_native_ad.dart';
import '../models/level_play_native_ad_template_style.dart';
import '../models/level_play_template_type.dart';
import '../models/ad_info.dart';
import '../models/ironsource_error.dart';

/// [LevelPlayNativeAdView] is the widget that contains the native ad elements
///  and must be created in order view native ad
class LevelPlayNativeAdView extends StatefulWidget {
  /// The native ad object that should be shown in the container
  final LevelPlayNativeAd? nativeAd;

  /// The native ad template type(small, medium) that used when showing the
  /// template native ads(when using custom it is not required)
  final LevelPlayTemplateType templateType;

  /// The desired width of the native ad view.
  final double? width;

  /// The desired height of the native ad view.
  final double? height;

  /// The styling options to apply on the native ad, when using custom it
  /// needs to be implemented in order to take action.
  final LevelPlayNativeAdTemplateStyle? templateStyle;

  /// A Callback to notify that the ad view container is successfully created and load ad is available.
  final VoidCallback? onPlatformViewCreated;

  /// Define the view type name to be used as custom template.
  final String viewType;

  /// Constructs an instance of [LevelPlayNativeAdView].
  const LevelPlayNativeAdView({
    super.key,
    required this.nativeAd,
    this.templateType = LevelPlayTemplateType.SMALL,
    this.width,
    this.height,
    this.templateStyle,
    this.onPlatformViewCreated,
    this.viewType = 'LevelPlayNativeAdView'
  });

  @override
  State<LevelPlayNativeAdView> createState() => _LevelPlayNativeAdViewState();
}

class _LevelPlayNativeAdViewState extends State<LevelPlayNativeAdView> {
  MethodChannel? _channel;
  
  /// Invoked when the platform view for the native ad is created.
  /// Initialize the method channel and load ad if needed.
  void _onPlatformViewCreated(int id) {
    final String methodChannelName = "${widget.viewType}_$id";
    // Create method channel with the unique id generated by the platform initialization
    _channel = MethodChannel(methodChannelName);
    
    // Set up method call handler to receive events from native
    _channel?.setMethodCallHandler(_handleMethodCall);
    
    // Set up command callbacks on the native ad
    widget.nativeAd?.setLoadAdCallback(() {
      _channel?.invokeMethod('loadAd');
    });
    
    widget.nativeAd?.setDestroyAdCallback(() {
      _channel?.invokeMethod('destroyAd');
    });
    
    // Notify on ad view creation
    widget.onPlatformViewCreated?.call();
  }
  
  /// Handle method calls from native platform (events)
  Future<dynamic> _handleMethodCall(MethodCall call) async {
    final nativeAd = widget.nativeAd;
    if (nativeAd == null) return;
    
    switch (call.method) {
      case 'onAdLoaded':
        final nativeAd = _extractCompletedNativeAd(call.arguments);
        final adInfo = AdInfo.fromMap(call.arguments['adInfo']);
        nativeAd.listener?.onAdLoaded(nativeAd, adInfo);
        break;
      case 'onAdLoadFailed':
        final nativeAd = _extractCompletedNativeAd(call.arguments);
        final error = IronSourceError.fromMap(call.arguments['error']);
        nativeAd.listener?.onAdLoadFailed(nativeAd, error);
        break;
      case 'onAdImpression':
        final nativeAd = _extractCompletedNativeAd(call.arguments);
        final adInfo = AdInfo.fromMap(call.arguments['adInfo']);
        nativeAd.listener?.onAdImpression(nativeAd, adInfo);
        break;
      case 'onAdClicked':
        final nativeAd = _extractCompletedNativeAd(call.arguments);
        final adInfo = AdInfo.fromMap(call.arguments['adInfo']);
        nativeAd.listener?.onAdClicked(nativeAd, adInfo);
        break;
      default:
        break;
    }
  }
  
  /// Extract and complete the native ad object from method call arguments
  LevelPlayNativeAd _extractCompletedNativeAd(dynamic args) {
    final nativeAd = LevelPlayNativeAd.fromMap(args['nativeAd']);
    // Copy existing variables to complete the native ad object
    nativeAd.listener = widget.nativeAd?.listener;
    nativeAd.placementName = widget.nativeAd?.placementName;
    return nativeAd;
  }
  
  @override
  void dispose() {
    _channel?.setMethodCallHandler(null);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final creationParams = <String, dynamic>{
      "placement": widget.nativeAd?.placementName ?? '',
      "templateType": widget.templateType.value,
      "templateStyle": widget.templateStyle?.toMap(),
      "viewType": widget.viewType
    };

    return SizedBox(
      width: widget.width,
      height: widget.height,
      child: Platform.isAndroid ? AndroidView(
        viewType: widget.viewType,
        creationParams: creationParams,
        creationParamsCodec: const StandardMessageCodec(),
        onPlatformViewCreated: _onPlatformViewCreated,
        ) :
        Platform.isIOS ? UiKitView(
            viewType: widget.viewType,
            creationParams: creationParams,
            creationParamsCodec: const StandardMessageCodec(),
            onPlatformViewCreated: _onPlatformViewCreated) : Container(),
    );
  }
}